{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funczz",
    "module": "rocket-launcher-core",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.funczz",
          "module": "fsm",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.funczz",
          "module": "sam",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "rocket-launcher-core-0.2.0.jar",
          "url": "rocket-launcher-core-0.2.0.jar",
          "size": 42108,
          "sha512": "169ef422655a17a862d07e2134480b88f794742318732638ad7c2028b6e848765706fae40d6402f2965baa59a73dcbb916ad7f2b46a3b9629a39989cb16a25d7",
          "sha256": "fb1436c30d519004c4d75511a3f26f27f7dc3fd141014f82ccf062616362c0e4",
          "sha1": "07b9ad0bdda3fc6541a639a5535f919d9bb8ace0",
          "md5": "d63fd7a387aaed4096e466e0125b249a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.funczz",
          "module": "fsm",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.github.funczz",
          "module": "sam",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "rocket-launcher-core-0.2.0.jar",
          "url": "rocket-launcher-core-0.2.0.jar",
          "size": 42108,
          "sha512": "169ef422655a17a862d07e2134480b88f794742318732638ad7c2028b6e848765706fae40d6402f2965baa59a73dcbb916ad7f2b46a3b9629a39989cb16a25d7",
          "sha256": "fb1436c30d519004c4d75511a3f26f27f7dc3fd141014f82ccf062616362c0e4",
          "sha1": "07b9ad0bdda3fc6541a639a5535f919d9bb8ace0",
          "md5": "d63fd7a387aaed4096e466e0125b249a"
        }
      ]
    }
  ]
}
